<a href="https://colab.research.google.com/github/satrishabh/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
b=np.array([[1,2,3,4],[5,6,7,8]])

In [5]:
print(a)
print("-"*50)
print(b)

[1 2 3 4]
--------------------------------------------------
[[1 2 3 4]
 [5 6 7 8]]


In [7]:
array=np.arange(1,11)

In [10]:
print(array)
dim=array.ndim
print(dim)

[ 1  2  3  4  5  6  7  8  9 10]
1


In [12]:
reshaped=array.reshape(5,2)
new_dim = reshaped.ndim
print(new_dim)


2


In [14]:
array=np.eye(4,dtype='float32')
print(array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
marks = np.array([20, 30, 40])
# ID array
ids = np.linspace(0,4,3)
# display marks and id array
print(marks)
print(ids)

# Code ends here

[20 30 40]
[0. 2. 4.]


In [21]:
array=np.array([3,4.5,4+5j,0])
real=np.isreal(array)
array_real=array[real]
print(array_real)
print(real)
print('-'*30)
imag=np.iscomplex(array)
array_imag=array[imag]
print(array_imag)
print(imag)

[3. +0.j 4.5+0.j 0. +0.j]
[ True  True False  True]
------------------------------
[4.+5.j]
[False False  True False]


In [25]:
vector=np.array([1,2,3,4,5,6,7])
print(vector[vector>2])

[3 4 5 6 7]


In [34]:
##buy and sell stocks
price=[[40,35,20],[21,48,70]]
prices=np.array(price)
print(prices)
prices=prices.flatten()
buying_price=np.min(prices)
index=list(prices).index(buying_price)
new_prices=prices[index:]
selling_prices=np.max(new_prices)
profit=selling_prices-buying_price
print(profit)

[[40 35 20]
 [21 48 70]]
50


In [35]:
np.random.seed(21)

# Code starts here

# create random 5x5 array
Z = np.random.random((5,5))

# minimum and maximum values
Zmax, Zmin = Z.max(), Z.min()

# normalize
Z_norm = (Z - Zmin)/(Zmax - Zmin)

# display
print(Z_norm)

# Code ends here

[[0.02856942 0.28190767 0.73703555 0.         0.19423813]
 [0.03072817 0.29577917 0.67690496 0.3019365  0.59225784]
 [0.05053881 0.89136471 0.1176393  0.16494209 0.49987233]
 [0.88746023 0.77705951 1.         0.77743756 0.38217481]
 [0.40796162 0.72901978 0.26247412 0.87734633 0.93959001]]
